export enum contractType {
    TEMPO_INTEGRAL = 'TEMPO_INTEGRAL',
    MEIO_PERIODO = 'MEIO_PERIODO',
    CONTRATO = 'CONTRATO',
    ESTAGIO = 'ESTAGIO',
    TEMPORARIO = 'TEMPORARIO',
    FREELANCER = 'FREELANCER',
    OUTRO = 'OUTRO',
}
